"""Convert guid to string

Revision ID: 7ca3c9115d10
Revises: 1c59765cc871
Create Date: 2024-07-28 22:21:37.691333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca3c9115d10'
down_revision = '1c59765cc871'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
