"""Change the default value for guid

Revision ID: 1c59765cc871
Revises: 96d4164ad292
Create Date: 2024-07-28 22:19:24.771387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c59765cc871'
down_revision = '96d4164ad292'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
